source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'BSQRCodeReader_Example', :exclusive => true do
  pod 'BSQRCodeReader', :path => '../'
end

target 'BSQRCodeReader_Tests', :exclusive => true do
  pod 'BSQRCodeReader', :path => '../'

  
end
